print("weather is sunny at the moment")
print("Batumi is the city of georgia")
print("rearrange this car here")
print("write parentheses here")
print("this pencils are variety")
print("this is incorect answer")
print("we loss last match")
print("i select this car")
print("please help me to handle this problem")
print("tell me your problem")
print("teacher surving us at the moment")
print("im ensured with everything")
print("twins are similar")
print("this looks much explicit")